apiVersion: v1
kind: Service
metadata:
  name: {{ include "chaincode.fullname" . }}
  labels:
    {{- include "chaincode.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 7052
      protocol: TCP
      name: grpc
  selector:
    {{- include "chaincode.selectorLabels" . | nindent 4 }}
